const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('statusApp', {
  getTabs: () => ipcRenderer.invoke('get-tabs'),
  getColumns: (tab) => ipcRenderer.invoke('get-columns', tab),
  getOptions: () => ipcRenderer.invoke('get-options'),
  getFieldSchema: () => ipcRenderer.invoke('get-field-schema'),
  getCategories: () => ipcRenderer.invoke('get-categories'),
  saveOptions: (options) => ipcRenderer.invoke('save-options', options),
  saveFieldSchema: (fieldSchema) => ipcRenderer.invoke('save-field-schema', fieldSchema),
  saveCategories: (categories) => ipcRenderer.invoke('save-categories', categories),
  getReportSettings: () => ipcRenderer.invoke('get-report-settings'),
  saveReportSettings: (settings) => ipcRenderer.invoke('save-report-settings', settings),
  submitEntry: (tab, values) => ipcRenderer.invoke('submit-entry', { tab, values }),
  sendReportNow: (range) => ipcRenderer.invoke('send-report-now', range),
  downloadReport: (range) => ipcRenderer.invoke('download-report', range),
  getNextNumber: (tab, column) => ipcRenderer.invoke('get-next-number', { tab, column }),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  checkLatestVersion: () => ipcRenderer.invoke('check-latest-version'),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  getYourName: () => ipcRenderer.invoke('get-your-name'),
  hideWindow: () => ipcRenderer.invoke('hide-window'),
  openSheet: () => ipcRenderer.invoke('open-sheet'),
  fabClicked: () => ipcRenderer.invoke('fab-clicked'),
  showFabMenu: () => ipcRenderer.invoke('show-fab-menu'),
  saveYourName: (name) => ipcRenderer.invoke('save-your-name', name),
  onOpened: (callback) => ipcRenderer.on('opened', callback),
  onSubmitRetry: (callback) => ipcRenderer.on('submit-retry', (_e, info) => callback(info)),
  resizeWindow: (height) => ipcRenderer.send('resize-window', height),
  moveFloatBtnBy: (dx, dy) => ipcRenderer.send('float-btn-move-by', { dx, dy }),
  setIgnoreMouseEvents: (ignore) => ipcRenderer.send('float-btn-set-ignore-mouse', ignore),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
  hasConnectionConfig: () => ipcRenderer.invoke('has-connection-config'),
  verifyAdminPassword: (password) => ipcRenderer.invoke('verify-admin-password', password),
  getConnectionConfig: () => ipcRenderer.invoke('get-connection-config'),
  saveConnectionConfig: (conn) => ipcRenderer.invoke('save-connection-config', conn),
  openConnectionSettings: () => ipcRenderer.invoke('open-connection-settings'),
  openManageScreen: () => ipcRenderer.invoke('open-manage-screen'),
});
