const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('statusApp', {
  getTabs: () => ipcRenderer.invoke('get-tabs'),
  getColumns: (tab) => ipcRenderer.invoke('get-columns', tab),
  getOptions: () => ipcRenderer.invoke('get-options'),
  getFieldSchema: () => ipcRenderer.invoke('get-field-schema'),
  getCategories: () => ipcRenderer.invoke('get-categories'),
  saveOptions: (options) => ipcRenderer.invoke('save-options', options),
  saveFieldSchema: (fieldSchema) => ipcRenderer.invoke('save-field-schema', fieldSchema),
  saveCategories: (categories) => ipcRenderer.invoke('save-categories', categories),
  getReportSettings: () => ipcRenderer.invoke('get-report-settings'),
  saveReportSettings: (settings) => ipcRenderer.invoke('save-report-settings', settings),
  renameTab: (oldName, newName) => ipcRenderer.invoke('rename-tab', { oldName, newName }),
  submitAdminContact: (payload) => ipcRenderer.invoke('submit-admin-contact', payload),
  getReportConfigs: () => ipcRenderer.invoke('get-report-configs'),
  saveReportConfigs: (configs) => ipcRenderer.invoke('save-report-configs', configs),
  getConnectGroups: () => ipcRenderer.invoke('get-connect-groups'),
  saveConnectGroups: (groups) => ipcRenderer.invoke('save-connect-groups', groups),
  getSessionStatus: () => ipcRenderer.invoke('get-session-status'),
  login: (username, password) => ipcRenderer.invoke('login', { username, password }),
  logout: () => ipcRenderer.invoke('logout'),
  listUsers: () => ipcRenderer.invoke('list-users'),
  createUser: (username, password, role) => ipcRenderer.invoke('create-user', { username, password, role }),
  resetUserPassword: (username, newPassword) => ipcRenderer.invoke('reset-user-password', { username, newPassword }),
  setUserActive: (username, active) => ipcRenderer.invoke('set-user-active', { username, active }),
  setUserRole: (username, role) => ipcRenderer.invoke('set-user-role', { username, role }),
  getWeeklyConnectTickets: () => ipcRenderer.invoke('get-weekly-connect-tickets'),
  updateWeeklyConnectTicket: (ticketId, status, comments) =>
    ipcRenderer.invoke('update-weekly-connect-ticket', { ticketId, status, comments }),
  postWeeklyConnectToTeamsNow: (group, range) =>
    ipcRenderer.invoke('post-weekly-connect-to-teams', { group, range }),
  submitEntry: (tab, values) => ipcRenderer.invoke('submit-entry', { tab, values }),
  sendReportNow: (range, configName) => ipcRenderer.invoke('send-report-now', { range, configName }),
  downloadReport: (range, configName) => ipcRenderer.invoke('download-report', { range, configName }),
  getNextNumber: (tab, column) => ipcRenderer.invoke('get-next-number', { tab, column }),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  getAppInfo: () => ipcRenderer.invoke('get-app-info'),
  checkLatestVersion: () => ipcRenderer.invoke('check-latest-version'),
  isUpdateReadyToInstall: () => ipcRenderer.invoke('is-update-ready-to-install'),
  quitAndInstall: () => ipcRenderer.invoke('quit-and-install'),
  onUpdateDownloaded: (callback) => ipcRenderer.on('update-downloaded', callback),
  openExternal: (url) => ipcRenderer.invoke('open-external', url),
  getYourName: () => ipcRenderer.invoke('get-your-name'),
  hideWindow: () => ipcRenderer.invoke('hide-window'),
  openSheet: () => ipcRenderer.invoke('open-sheet'),
  fabClicked: () => ipcRenderer.invoke('fab-clicked'),
  showFabMenu: () => ipcRenderer.invoke('show-fab-menu'),
  saveYourName: (name) => ipcRenderer.invoke('save-your-name', name),
  onOpened: (callback) => ipcRenderer.on('opened', callback),
  onSubmitRetry: (callback) => ipcRenderer.on('submit-retry', (_e, info) => callback(info)),
  resizeWindow: (height) => ipcRenderer.send('resize-window', height),
  moveFloatBtnBy: (dx, dy) => ipcRenderer.send('float-btn-move-by', { dx, dy }),
  setIgnoreMouseEvents: (ignore) => ipcRenderer.send('float-btn-set-ignore-mouse', ignore),
  clearCache: () => ipcRenderer.invoke('clear-cache'),
  hasConnectionConfig: () => ipcRenderer.invoke('has-connection-config'),
  verifyAdminPassword: (password) => ipcRenderer.invoke('verify-admin-password', password),
  getConnectionConfig: () => ipcRenderer.invoke('get-connection-config'),
  saveConnectionConfig: (conn) => ipcRenderer.invoke('save-connection-config', conn),
  openConnectionSettings: () => ipcRenderer.invoke('open-connection-settings'),
  openManageScreen: () => ipcRenderer.invoke('open-manage-screen'),
});
